// Roughens schematic diagrams with Rough.js at build time.
//   node tools/diagrams/sketch.mjs            (npm run sketch)
// Reads tools/diagrams/schematics/*.svg, replaces every <rect|circle|ellipse|line|polygon|path ... class="sketch ...">
// with hand-drawn path data, and writes content/diagrams/<slug>.svg. Fixed seed, so the output is stable.
// Attributes: fill/stroke/stroke-width are honoured (token colours pass through); data-fill-style="hachure|solid|
// zigzag|cross-hatch|dots" picks the fill, data-roughness overrides the default 1.
import rough from "roughjs/bundled/rough.esm.js";
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, join } from "node:path";

const root = new URL("../..", import.meta.url).pathname;
const srcDir = join(root, "tools/diagrams/schematics");
const outDir = join(root, "content/diagrams");
const gen = rough.generator();

const SHAPE = /<(rect|circle|ellipse|line|polygon|path)\b([^>]*?)\bclass="([^"]*\bsketch\b[^"]*)"([^>]*?)\/>/g;

function attrs(s) {
  const o = {};
  for (const m of s.matchAll(/([\w:-]+)="([^"]*)"/g)) o[m[1]] = m[2];
  return o;
}
const num = (v, d = 0) => (v === undefined ? d : Number(v));

function sketch(tag, a, seed) {
  const fill = a.fill && a.fill !== "none" ? a.fill : undefined;
  const o = {
    seed, roughness: num(a["data-roughness"], 1), bowing: 0.8,
    stroke: a.stroke && a.stroke !== "none" ? a.stroke : "none",
    strokeWidth: num(a["stroke-width"], 2),
    fill, fillStyle: a["data-fill-style"] || (fill ? "hachure" : undefined), hachureGap: num(a["data-hachure-gap"], 6), fillWeight: 1,
    hachureAngle: num(a["data-hachure-angle"], -41),
  };
  switch (tag) {
    case "rect": return gen.rectangle(num(a.x), num(a.y), num(a.width), num(a.height), o);
    case "circle": return gen.circle(num(a.cx), num(a.cy), 2 * num(a.r), o);
    case "ellipse": return gen.ellipse(num(a.cx), num(a.cy), 2 * num(a.rx), 2 * num(a.ry), o);
    case "line": return gen.line(num(a.x1), num(a.y1), num(a.x2), num(a.y2), o);
    case "polygon": return gen.polygon(a.points.trim().split(/\s+/).map((p) => p.split(",").map(Number)), o);
    case "path": return gen.path(a.d, o);
  }
}

function toSvg(drawable, a) {
  const keep = ["transform", "opacity", "stroke-dasharray", "stroke-linecap", "stroke-linejoin", "id"].filter((k) => a[k]).map((k) => ` ${k}="${a[k]}"`).join("");
  const cls = a.class.replace(/\bsketch\b/, "").trim();
  const paths = gen.toPaths(drawable).map((p) => {
    const isFill = p.fill && p.fill !== "none";
    const fillAttr = isFill ? ` fill="${p.fill}"` : ' fill="none"';
    const strokeAttr = p.stroke && p.stroke !== "none" ? ` stroke="${p.stroke}" stroke-width="${round(p.strokeWidth)}"` : "";
    return `<path d="${p.d}"${fillAttr}${strokeAttr} stroke-linecap="round" stroke-linejoin="round"/>`;
  });
  return `<g${cls ? ` class="${cls}"` : ""}${keep}>${paths.join("")}</g>`;
}
const round = (v) => Math.round(v * 100) / 100;

mkdirSync(outDir, { recursive: true });
let n = 0;
for (const f of readdirSync(srcDir).filter((f) => f.endsWith(".svg"))) {
  const slug = basename(f, ".svg");
  let seed = 1;
  let svg = readFileSync(join(srcDir, f), "utf8");
  svg = svg.replace(SHAPE, (m, tag, before, cls, after) => {
    const a = { ...attrs(before), ...attrs(after), class: cls };
    return toSvg(sketch(tag, a, seed++), a);
  });
  // tidy: round long decimals in path data
  svg = svg.replace(/(\d+\.\d{3,})/g, (v) => String(Math.round(Number(v) * 100) / 100));
  const marker = "<!-- generated by tools/diagrams/sketch.mjs from tools/diagrams/schematics/" + f + "; edit the schematic, not this file -->\n";
  writeFileSync(join(outDir, slug + ".svg"), marker + svg.replace(/^<!--.*?-->\s*/s, ""));
  n++;
}
console.log(`${n} schematic(s) sketched into content/diagrams`);
