"""Small SVG toolkit for the note diagrams. Emits token-coloured SVG that follows the style guide in
content/diagrams/README.md. Every helper returns a string of SVG markup; Canvas assembles them.

    from tools.diagrams.svg import Canvas, Chart, text, arrow, plane_side
    c = Canvas("Forces in level flight", "Lift up, weight down, thrust right, drag left", prefix="flf")
    c.add(plane_side(320, 180, scale=2.4))
    c.add(arrow(320, 150, 320, 60, color="brand", label="Lift"))
    c.write("forces-level-flight")

Coordinates are viewBox units: 640 wide, 360 tall by default. Colours are token names ("brand", "fg",
"ok-soft"), turned into var(--color-…) by col().
"""
from __future__ import annotations

import math
from pathlib import Path
from xml.sax.saxutils import escape

ROOT = Path(__file__).resolve().parents[2]
DIAGRAMS = ROOT / "content" / "diagrams"
GENERATED = "<!-- generated by tools/diagrams; do not edit, change the generator and run `python -m tools.diagrams.build` -->"

W, H = 640, 360
MAIN, SECOND, THIN = 2, 1.25, 1
DASH = "4 3"


def col(token: str | None) -> str:
    """'brand' -> 'var(--color-brand)'. Passes through 'none', 'currentColor' and existing var()/url() values."""
    if token is None:
        return "none"
    if not isinstance(token, str):
        raise TypeError(f"colour token expected, got {token!r} (check the argument order: stroke, fill, width)")
    if token in ("none", "currentColor", "transparent", "inherit", "context-stroke", "context-fill") or token.startswith(("var(", "url(")):
        return token
    return f"var(--color-{token})"


def fmt(v: float) -> str:
    return f"{v:.2f}".rstrip("0").rstrip(".") if isinstance(v, float) else str(v)


def attrs(**kw) -> str:
    """Keyword args to attributes; underscores become hyphens, None values are skipped."""
    parts = []
    for k, v in kw.items():
        if v is None or v is False:
            continue
        k = k.rstrip("_").replace("_", "-")
        if k == "cls":
            k = "class"
        parts.append(f'{k}="{escape(str(v), {chr(34): "&quot;"})}"')
    return (" " + " ".join(parts)) if parts else ""


# ---------------------------------------------------------------- primitives
def text(x: float, y: float, s: str, size: float = 13, anchor: str = "start", color: str = "fg", weight: str | int | None = None,
         cls: str | None = None, baseline: str | None = None, rotate: float | None = None, italic: bool = False, opacity: float | None = None) -> str:
    tf = f"rotate({fmt(rotate)} {fmt(x)} {fmt(y)})" if rotate else None
    return (f"<text{attrs(x=fmt(x), y=fmt(y), font_size=fmt(size), text_anchor=None if anchor == 'start' else anchor, fill=col(color), font_weight=weight, cls=cls, dominant_baseline=baseline, transform=tf, font_style='italic' if italic else None, opacity=opacity)}>"
            f"{escape(s)}</text>")


def num(x: float, y: float, s: str, size: float = 13, anchor: str = "start", color: str = "fg", **kw) -> str:
    """Tabular numbers in the mono font (class num)."""
    return text(x, y, s, size, anchor, color, cls="num", **kw)


def multiline(x: float, y: float, lines: list[str], size: float = 13, anchor: str = "start", color: str = "fg", leading: float = 1.3, **kw) -> str:
    return "".join(text(x, y + i * size * leading, s, size, anchor, color, **kw) for i, s in enumerate(lines))


def line(x1: float, y1: float, x2: float, y2: float, color: str = "fg", width: float = MAIN, dash: str | None = None,
         arrow_end: bool = False, arrow_start: bool = False, cls: str | None = None, opacity: float | None = None, cap: str = "round") -> str:
    return f"<line{attrs(x1=fmt(x1), y1=fmt(y1), x2=fmt(x2), y2=fmt(y2), stroke=col(color), stroke_width=fmt(width), stroke_dasharray=dash, stroke_linecap=cap, marker_end='url(#arrow)' if arrow_end else None, marker_start='url(#arrow)' if arrow_start else None, cls=cls, opacity=opacity)}/>"


def arrow(x1: float, y1: float, x2: float, y2: float, color: str = "brand", width: float = MAIN, label: str | None = None,
          label_size: float = 13, label_offset: float = 10, label_side: str = "auto", dash: str | None = None, both: bool = False,
          cls: str | None = None, label_weight: str | int | None = 600) -> str:
    """Arrow from (x1,y1) to (x2,y2) with an optional label placed beside the midpoint, clear of the shaft."""
    out = line(x1, y1, x2, y2, color, width, dash, arrow_end=True, arrow_start=both, cls=cls)
    if label:
        mx, my = (x1 + x2) / 2, (y1 + y2) / 2
        dx, dy = x2 - x1, y2 - y1
        length = math.hypot(dx, dy) or 1
        nx, ny = -dy / length, dx / length  # left normal
        if label_side == "right" or (label_side == "auto" and nx < 0):
            nx, ny = -nx, -ny
        lx, ly = mx + nx * label_offset, my + ny * label_offset
        anchor = "start" if nx > 0.3 else "end" if nx < -0.3 else "middle"
        out += text(lx, ly + label_size * 0.35, label, label_size, anchor, color, weight=label_weight)
    return out


def path(d: str, stroke: str | None = "fg", fill: str | None = None, width: float = MAIN, dash: str | None = None, cls: str | None = None,
         opacity: float | None = None, fill_opacity: float | None = None, transform: str | None = None, arrow_end: bool = False, join: str = "round") -> str:
    return f"<path{attrs(d=d, stroke=col(stroke), stroke_width=fmt(width) if stroke else None, fill=col(fill), stroke_dasharray=dash, stroke_linecap='round' if stroke else None, stroke_linejoin=join if stroke else None, cls=cls, opacity=opacity, fill_opacity=fill_opacity, transform=transform, marker_end='url(#arrow)' if arrow_end else None)}/>"


def rect(x: float, y: float, w: float, h: float, fill: str | None = "surface", stroke: str | None = "fg", width: float = MAIN, rx: float | None = None,
         cls: str | None = None, opacity: float | None = None, fill_opacity: float | None = None, dash: str | None = None, transform: str | None = None) -> str:
    return f"<rect{attrs(x=fmt(x), y=fmt(y), width=fmt(w), height=fmt(h), rx=fmt(rx) if rx else None, fill=col(fill), stroke=col(stroke), stroke_width=fmt(width) if stroke else None, stroke_dasharray=dash, cls=cls, opacity=opacity, fill_opacity=fill_opacity, transform=transform)}/>"


def circle(cx: float, cy: float, r: float, fill: str | None = "surface", stroke: str | None = "fg", width: float = MAIN, cls: str | None = None,
           opacity: float | None = None, fill_opacity: float | None = None, dash: str | None = None) -> str:
    return f"<circle{attrs(cx=fmt(cx), cy=fmt(cy), r=fmt(r), fill=col(fill), stroke=col(stroke), stroke_width=fmt(width) if stroke else None, stroke_dasharray=dash, cls=cls, opacity=opacity, fill_opacity=fill_opacity)}/>"


def ellipse(cx: float, cy: float, rx: float, ry: float, fill: str | None = "surface", stroke: str | None = "fg", width: float = MAIN, cls: str | None = None,
            opacity: float | None = None, fill_opacity: float | None = None, transform: str | None = None) -> str:
    return f"<ellipse{attrs(cx=fmt(cx), cy=fmt(cy), rx=fmt(rx), ry=fmt(ry), fill=col(fill), stroke=col(stroke), stroke_width=fmt(width) if stroke else None, cls=cls, opacity=opacity, fill_opacity=fill_opacity, transform=transform)}/>"


def polygon(points: list[tuple[float, float]], fill: str | None = "surface", stroke: str | None = "fg", width: float = MAIN, cls: str | None = None,
            opacity: float | None = None, fill_opacity: float | None = None, transform: str | None = None) -> str:
    pts = " ".join(f"{fmt(x)},{fmt(y)}" for x, y in points)
    return f"<polygon{attrs(points=pts, fill=col(fill), stroke=col(stroke), stroke_width=fmt(width) if stroke else None, stroke_linejoin='round', cls=cls, opacity=opacity, fill_opacity=fill_opacity, transform=transform)}/>"


def polyline(points: list[tuple[float, float]], stroke: str = "fg", width: float = MAIN, dash: str | None = None, cls: str | None = None,
             arrow_end: bool = False, opacity: float | None = None, fill: str | None = None) -> str:
    pts = " ".join(f"{fmt(x)},{fmt(y)}" for x, y in points)
    return f"<polyline{attrs(points=pts, fill=col(fill), stroke=col(stroke), stroke_width=fmt(width), stroke_dasharray=dash, stroke_linecap='round', stroke_linejoin='round', cls=cls, marker_end='url(#arrow)' if arrow_end else None, opacity=opacity)}/>"


def group(*children: str, transform: str | None = None, cls: str | None = None, opacity: float | None = None, id_: str | None = None, style: str | None = None) -> str:
    return f"<g{attrs(transform=transform, cls=cls, opacity=opacity, id=id_, style=style)}>{''.join(children)}</g>"


def smooth_path(points: list[tuple[float, float]], closed: bool = False) -> str:
    """Catmull-Rom through the points as cubic Béziers: a smooth curve for airflow, wakes, graphs."""
    if len(points) < 2:
        return ""
    pts = list(points)
    if closed:
        pts = [pts[-1]] + pts + [pts[0], pts[1]]
    else:
        pts = [pts[0]] + pts + [pts[-1]]
    d = f"M{fmt(pts[1][0])} {fmt(pts[1][1])}"
    for i in range(1, len(pts) - 2):
        p0, p1, p2, p3 = pts[i - 1], pts[i], pts[i + 1], pts[i + 2]
        c1 = (p1[0] + (p2[0] - p0[0]) / 6, p1[1] + (p2[1] - p0[1]) / 6)
        c2 = (p2[0] - (p3[0] - p1[0]) / 6, p2[1] - (p3[1] - p1[1]) / 6)
        d += f" C{fmt(c1[0])} {fmt(c1[1])} {fmt(c2[0])} {fmt(c2[1])} {fmt(p2[0])} {fmt(p2[1])}"
    return d + (" Z" if closed else "")


def arc_path(cx: float, cy: float, r: float, a0: float, a1: float) -> str:
    """Arc from angle a0 to a1 (degrees, 0 = +x, clockwise positive in screen space)."""
    x0, y0 = cx + r * math.cos(math.radians(a0)), cy + r * math.sin(math.radians(a0))
    x1, y1 = cx + r * math.cos(math.radians(a1)), cy + r * math.sin(math.radians(a1))
    large = 1 if abs(a1 - a0) > 180 else 0
    sweep = 1 if a1 > a0 else 0
    return f"M{fmt(x0)} {fmt(y0)} A{fmt(r)} {fmt(r)} 0 {large} {sweep} {fmt(x1)} {fmt(y1)}"


def angle_mark(cx: float, cy: float, r: float, a0: float, a1: float, label: str | None = None, color: str = "fg-muted", size: float = 13) -> str:
    """Angle indicator: an arc between two directions with the label just outside its middle."""
    out = path(arc_path(cx, cy, r, a0, a1), stroke=color, width=SECOND)
    if label:
        am = math.radians((a0 + a1) / 2)
        lx, ly = cx + (r + 12) * math.cos(am), cy + (r + 12) * math.sin(am)
        out += text(lx, ly + size * 0.35, label, size, "middle", color)
    return out


def callout(x: float, y: float, tx: float, ty: float, lines: str | list[str], color: str = "fg", size: float = 13, dot: bool = True, anchor: str | None = None) -> str:
    """Leader line from a point (x,y) to a label at (tx,ty). Text anchors away from the point."""
    if isinstance(lines, str):
        lines = [lines]
    anchor = anchor or ("start" if tx >= x else "end")
    gap = 6 if anchor == "start" else -6
    out = line(x, y, tx, ty, "fg-muted", THIN) + (circle(x, y, 2.5, color, None) if dot else "")
    out += multiline(tx + gap, ty + size * 0.35, lines, size, anchor, color)
    return out


def badge(x: float, y: float, s: str, color: str = "brand", size: float = 12) -> str:
    """Small rounded label (pill) centred on x,y, used for leg names, states and short tags."""
    w = len(s) * size * 0.62 + 14
    return rect(x - w / 2, y - size * 0.8, w, size * 1.6, f"{color}-soft" if color in ("brand", "ok", "warn", "bad", "info") else "surface-2", None, rx=size * 0.8) + \
        text(x, y + size * 0.35, s, size, "middle", f"{color}-fg" if color in ("brand", "ok", "warn", "bad", "info") else "fg", weight=600)


# ---------------------------------------------------------------- recurring characters
def plane_side(x: float, y: float, scale: float = 1.0, color: str = "fg", pitch: float = 0, fill: str = "surface", prop: bool = True, gear: bool = True, cls: str | None = None) -> str:
    """Low-wing single-engine aeroplane seen from the left, nose to the right, ~100 units long at scale 1.
    (x, y) is the centre of gravity; pitch is nose-up degrees (screen rotation is negative)."""
    body = path("M50 0 C50 -4 46 -7 40 -8 L8 -10 C-4 -10 -22 -7 -40 -4 L-48 -3 L-48 3 L-40 4 C-22 6 -4 7 8 7 L42 6 C47 5 50 4 50 0 Z", color, fill, MAIN)
    fin = path("M-29 -4 L-39 -26 L-47 -26 L-48 -3 Z", color, fill, MAIN)
    tailplane = path("M-40 1 L-58 2 L-58 5 L-38 5 Z", color, fill, MAIN)
    wing = path("M18 2 C14 -1 -6 -1 -12 2 L-16 7 L14 7 C18 6 20 4 18 2 Z", color, fill, MAIN)
    window = path("M18 -9 L30 -9 L35 -5 L14 -5 Z", color, "surface-2", THIN)
    spinner = path("M50 -3 L57 0 L50 3 Z", color, fill, MAIN)
    parts = [tailplane, fin, body, wing, window, spinner]
    if prop:
        parts.append(line(55, -16, 55, 16, color, SECOND))
    if gear:
        parts += [line(10, 7, 10, 13, color, SECOND), circle(10, 15, 3.5, color, None), line(38, 6, 38, 12, color, SECOND), circle(38, 14, 3, color, None)]
    return group(*parts, transform=f"translate({fmt(x)} {fmt(y)}) rotate({fmt(-pitch)}) scale({fmt(scale)})", cls=cls)


def plane_top(x: float, y: float, scale: float = 1.0, heading: float = 90, color: str = "fg", fill: str = "surface", cls: str | None = None) -> str:
    """Aeroplane in plan view, ~100 units span at scale 1. heading in degrees (0 = up the page, 90 = to the right)."""
    body = path("M38 0 C38 -4 32 -5 26 -5 L-24 -3 L-34 -2 L-34 2 L-24 3 L26 5 C32 5 38 4 38 0 Z", color, fill, MAIN)
    wing = path("M12 -4 L4 -50 L-6 -50 L-8 -4 Z M12 4 L4 50 L-6 50 L-8 4 Z", color, fill, MAIN)
    tail = path("M-24 -2 L-28 -18 L-34 -18 L-34 -2 Z M-24 2 L-28 18 L-34 18 L-34 2 Z", color, fill, MAIN)
    spinner = path("M38 -2 L43 0 L38 2 Z", color, fill, MAIN)
    prop = line(41, -10, 41, 10, color, SECOND)
    return group(wing, tail, body, spinner, prop, transform=f"translate({fmt(x)} {fmt(y)}) rotate({fmt(heading - 90)}) scale({fmt(scale)})", cls=cls)


def plane_rear(x: float, y: float, scale: float = 1.0, bank: float = 0, color: str = "fg", fill: str = "surface", cls: str | None = None) -> str:
    """Aeroplane seen from behind, ~100 units span at scale 1. Positive bank rolls the left wing down
    (a left turn, as the pilot sees it: left wing on the reader's left)."""
    wing = path("M-50 -1 L-8 3 L-8 7 L-50 3 Z M50 -1 L8 3 L8 7 L50 3 Z", color, fill, MAIN)
    body = circle(0, 0, 9, fill, color, MAIN)
    fin = path("M-2 -8 L0 -28 L3 -28 L3 -8 Z", color, fill, MAIN)
    tailplane = path("M-17 -5 L17 -5 L17 -2 L-17 -2 Z", color, fill, MAIN)
    window = path("M-5 -6 L5 -6 L4 -2 L-4 -2 Z", color, "surface-2", THIN)
    return group(fin, tailplane, wing, body, window, transform=f"translate({fmt(x)} {fmt(y)}) rotate({fmt(-bank)}) scale({fmt(scale)})", cls=cls)


def aerofoil(x: float, y: float, chord: float = 60, angle: float = 0, color: str = "fg", fill: str = "surface", width: float = MAIN, cls: str | None = None) -> str:
    """Cambered aerofoil section, leading edge on the left (airflow from the left, wind-tunnel view), pitched leading-edge-up
    by `angle` degrees about its quarter-chord point (x, y)."""
    d = "M0 0 C8 -14 40 -16 100 -2 C60 4 20 8 0 0 Z"  # 100 units long
    return group(path(d, color, fill, width), transform=f"translate({fmt(x)} {fmt(y)}) rotate({fmt(angle)}) scale({fmt(chord / 100)}) translate(-25 0)", cls=cls)


def runway(x: float, y: float, length: float = 300, width: float = 30, number: str | None = "21", rotate: float = 0, cls: str | None = None) -> str:
    """Runway in plan view centred on (x, y), lying along x before rotation. Threshold at the left end."""
    parts = [rect(-length / 2, -width / 2, length, width, "tarmac", None, rx=1)]
    # centreline dashes
    n = int(length / 24)
    for i in range(1, n):
        x0 = -length / 2 + i * 24
        if 40 < x0 + length / 2 < length - 40:
            parts.append(line(x0, 0, x0 + 12, 0, "paint", width * 0.08, cap="butt"))
    # threshold stripes at both ends
    for sgn in (-1, 1):
        for j in range(4):
            yy = -width / 2 + width * (0.12 + j * 0.22)
            x0 = sgn * (length / 2 - 8)
            parts.append(rect(min(x0, x0 - sgn * 14), yy, 14, width * 0.12, "paint", None))
    if number:
        parts.append(text(-length / 2 + 32, width * 0.15, number, width * 0.45, "middle", "paint", weight=700, cls="num"))
    return group(*parts, transform=f"translate({fmt(x)} {fmt(y)}) rotate({fmt(rotate)})", cls=cls)


# ---------------------------------------------------------------- canvas
class Canvas:
    def __init__(self, title: str, desc: str, width: int = W, height: int = H, prefix: str | None = None, generated: bool = True, background: str | None = None):
        self.title, self.desc, self.width, self.height = title, desc, width, height
        self.prefix = prefix
        self.generated = generated
        self.parts: list[str] = []
        self.defs: list[str] = [ARROW_MARKER]
        self.css: list[str] = []
        if background:
            self.parts.append(rect(0, 0, width, height, background, None, rx=12))

    def add(self, *markup: str) -> "Canvas":
        self.parts.extend(markup)
        return self

    def add_defs(self, markup: str) -> "Canvas":
        self.defs.append(markup)
        return self

    def style(self, css: str) -> "Canvas":
        self.css.append(css.strip())
        return self

    def render(self) -> str:
        head = f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {self.width} {self.height}" role="img"' + (f' data-prefix="{self.prefix}"' if self.prefix else "") + ">"
        out = [GENERATED] if self.generated else []
        out += [head, f"<title>{escape(self.title)}</title>", f"<desc>{escape(self.desc)}</desc>"]
        if self.css:
            out.append("<style>" + "\n".join(self.css) + "</style>")
        out.append("<defs>" + "".join(self.defs) + "</defs>")
        out += self.parts
        out.append("</svg>")
        return "\n".join(out) + "\n"

    def write(self, slug: str, directory: Path = DIAGRAMS) -> Path:
        directory.mkdir(parents=True, exist_ok=True)
        p = directory / f"{slug}.svg"
        p.write_text(self.render(), encoding="utf-8")
        return p


ARROW_MARKER = ('<marker id="arrow" viewBox="0 0 8 8" refX="7" refY="4" markerWidth="5" markerHeight="5" orient="auto-start-reverse">'
                '<path d="M0 0 L8 4 L0 8 z" fill="context-stroke"/></marker>')


# ---------------------------------------------------------------- charts
class Chart:
    """Cartesian axes mapping data to the canvas. box = (left, top, right, bottom) in canvas units."""

    def __init__(self, canvas: Canvas, x: tuple[float, float], y: tuple[float, float], box: tuple[float, float, float, float] = (70, 30, 610, 300),
                 xlabel: str | None = None, ylabel: str | None = None, xticks: list[float] | None = None, yticks: list[float] | None = None,
                 xfmt=fmt, yfmt=fmt, grid: bool = True, tick_size: float = 12):
        self.c, self.x0, self.x1, self.y0, self.y1 = canvas, x[0], x[1], y[0], y[1]
        self.left, self.top, self.right, self.bottom = box
        self.xlabel, self.ylabel, self.xticks, self.yticks, self.xfmt, self.yfmt, self.grid, self.tick_size = xlabel, ylabel, xticks or [], yticks or [], xfmt, yfmt, grid, tick_size

    def px(self, x: float) -> float:
        return self.left + (x - self.x0) / (self.x1 - self.x0) * (self.right - self.left)

    def py(self, y: float) -> float:
        return self.bottom - (y - self.y0) / (self.y1 - self.y0) * (self.bottom - self.top)

    def pt(self, x: float, y: float) -> tuple[float, float]:
        return self.px(x), self.py(y)

    def axes(self, arrows: bool = True) -> str:
        parts = []
        if self.grid:
            for t in self.xticks:
                parts.append(line(self.px(t), self.top, self.px(t), self.bottom, "line", THIN))
            for t in self.yticks:
                parts.append(line(self.left, self.py(t), self.right, self.py(t), "line", THIN))
        parts.append(line(self.left, self.bottom, self.right + (8 if arrows else 0), self.bottom, "fg-muted", SECOND, arrow_end=arrows, cap="butt"))
        parts.append(line(self.left, self.bottom, self.left, self.top - (8 if arrows else 0), "fg-muted", SECOND, arrow_end=arrows, cap="butt"))
        for t in self.xticks:
            parts.append(num(self.px(t), self.bottom + 16, self.xfmt(t), self.tick_size, "middle", "fg-muted"))
        for t in self.yticks:
            parts.append(num(self.left - 8, self.py(t) + 4, self.yfmt(t), self.tick_size, "end", "fg-muted"))
        if self.xlabel:
            parts.append(text((self.left + self.right) / 2, self.bottom + 36, self.xlabel, 13, "middle", "fg-muted", weight=600))
        if self.ylabel:
            parts.append(text(18, (self.top + self.bottom) / 2, self.ylabel, 13, "middle", "fg-muted", weight=600, rotate=-90))
        return "".join(parts)

    def curve(self, points: list[tuple[float, float]], color: str = "brand", width: float = MAIN, dash: str | None = None, smooth: bool = True,
              label: str | None = None, label_at: int | None = None, label_dx: float = 8, label_dy: float = 0, label_anchor: str = "start", cls: str | None = None) -> str:
        pts = [self.pt(x, y) for x, y in points]
        d = smooth_path(pts) if smooth else "M" + " L".join(f"{fmt(x)} {fmt(y)}" for x, y in pts)
        out = path(d, color, None, width, dash, cls=cls)
        if label:
            i = len(pts) - 1 if label_at is None else label_at
            out += text(pts[i][0] + label_dx, pts[i][1] + label_dy + 4, label, 13, label_anchor, color, weight=600)
        return out

    def area(self, points: list[tuple[float, float]], color: str = "brand", opacity: float = 0.15, baseline: float | None = None) -> str:
        base = self.y0 if baseline is None else baseline
        pts = [self.pt(x, y) for x, y in points]
        d = smooth_path(pts) + f" L{fmt(pts[-1][0])} {fmt(self.py(base))} L{fmt(pts[0][0])} {fmt(self.py(base))} Z"
        return path(d, None, color, 0, fill_opacity=opacity)

    def band(self, x_from: float, x_to: float, color: str = "bad", opacity: float = 0.12) -> str:
        return rect(self.px(x_from), self.top, self.px(x_to) - self.px(x_from), self.bottom - self.top, color, None, fill_opacity=opacity)

    def point(self, x: float, y: float, color: str = "brand", r: float = 4.5, label: str | None = None, dx: float = 8, dy: float = -8, anchor: str = "start") -> str:
        X, Y = self.pt(x, y)
        out = circle(X, Y, r, color, "surface", 1.5)
        if label:
            out += text(X + dx, Y + dy, label, 13, anchor, color, weight=600, cls="num")
        return out

    def vline(self, x: float, color: str = "fg-muted", dash: str | None = DASH, label: str | None = None, y_to: float | None = None, size: float = 12) -> str:
        X = self.px(x)
        top = self.py(y_to) if y_to is not None else self.top
        out = line(X, self.bottom, X, top, color, THIN, dash)
        if label:
            out += text(X, top - 6, label, size, "middle", color)
        return out

    def hline(self, y: float, color: str = "fg-muted", dash: str | None = DASH, label: str | None = None, x_to: float | None = None, size: float = 12) -> str:
        Y = self.py(y)
        right = self.px(x_to) if x_to is not None else self.right
        out = line(self.left, Y, right, Y, color, THIN, dash)
        if label:
            out += text(right + 6, Y + 4, label, size, "start", color)
        return out

    def guide(self, x: float, y: float, color: str = "fg-muted") -> str:
        """Dashed drop lines from a point to both axes."""
        X, Y = self.pt(x, y)
        return line(X, Y, X, self.bottom, color, THIN, DASH) + line(X, Y, self.left, Y, color, THIN, DASH)

    def callout(self, x: float, y: float, dx: float, dy: float, lines: str | list[str], color: str = "fg", size: float = 13) -> str:
        X, Y = self.pt(x, y)
        return callout(X, Y, X + dx, Y + dy, lines, color, size)


def sample(fn, x0: float, x1: float, n: int = 60) -> list[tuple[float, float]]:
    """Evaluate fn on n+1 evenly spaced points."""
    return [(x0 + (x1 - x0) * i / n, fn(x0 + (x1 - x0) * i / n)) for i in range(n + 1)]
